global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  - job_name: 'kafka-connect'
    static_configs:
      - targets: ['connect:8083']

  - job_name: 'schema-registry'
    static_configs:
      - targets: ['schema-registry:8081']
